name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2']

    steps:
      - uses: actions/checkout@v4
      - name: Update packages
        run: sudo apt-get update
      - name: Install packages
        run: sudo apt-get -y install hledger
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}
      - name: Run tests
        run: |
          bundle exec rspec

  release:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs:
      - test
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple
